"""update models

Revision ID: edeb83e6bc75
Revises: b8971c850a37
Create Date: 2024-03-16 18:15:00.227090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeb83e6bc75'
down_revision: Union[str, None] = 'b8971c850a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SavedFile', sa.Column('type', sa.String(), nullable=True))
    op.add_column('SavedFile', sa.Column('user', sa.String(), nullable=True))
    op.add_column('SavedFile', sa.Column('trackerid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SavedFile', 'trackerid')
    op.drop_column('SavedFile', 'user')
    op.drop_column('SavedFile', 'type')
    # ### end Alembic commands ###
